# enable repo: epelã€PowerTools
- name: Check epel repo enabled
  command:
    cmd: dnf repolist enabled | grep epel
    warn: false
  changed_when: false
  register: ___repo_result

- name: enable epel repo.
  package:
    name:
      - epel-release
    state: present
  when:
    - ___repo_result.stdout == ""

- name: Check PowerTools repo enabled
  command:
    cmd: dnf repolist enabled | grep PowerTools
    warn: false
  changed_when: false
  register: ___repo_result

- name: enable PowerTools repo.
  command:
    cmd: >
      {{ item }}
    warn: false
  with_items:
    - yum config-manager --set-enabled PowerTools
    - yum clean all
    - yum makecache
  when:
    - ___repo_result.stdout == ""
